repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.7.2
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix, --select, I]
          # Run the formatter.
          - id: ruff-format
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.0
      hooks:
          - id: pyupgrade
            args: [--py310-plus]
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.30.0
      hooks:
          - id: commitizen
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v1.13.0" # Use the sha / tag you want to point at
      hooks:
          - id: mypy
