# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytorch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pytorch: [
          'torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cpu',
          'torch==2.0.1 torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cpu',
          'torch==1.13.1+cpu torchvision==0.14.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu',
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.pytorch }}
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          python -m pytest
