#!/bin/bash
#SBATCH -p=gpu_4
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=55gb
#SBATCH --time=30:00:00
#SBATCH --job-name=RAFT_Chairs_val
#SBATCH --output=slurm/RAFT_chairs_val_%A.out
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:1
#SBATCH --error=slurm/RAFT_chairs_val_ERR_%A.out

echo RAFT_Chairs_val
#cd /ptlflow
python validate.py raft --pretrained_ckpt chairs --val_dataset chairs-val


#siff jobidvdsvah<c 